# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Integration


#on block specifies when we want to run this block
on:
  
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  #job is going to run on a server which is hosted by github
    runs-on: ubuntu-latest
#stragegy allows to to setup multiple different node versions
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
# these are the steps we need to take to run our job correctly 
    steps:

    - uses: actions/checkout@v3  #checking out feature branch
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3   # setting up node js in ubuntu server 
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci # i to install all the dependencies
    - run: npm run build --if-present
    - run: npm test
